
lora:
  r: 16
  lora_alpha: 16
  dropout: 0
  bias: none
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  use_gradient_checkpointing: unsloth
  random_state: 3407
  use_rslora: False
  loftq_config: None